
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: gregory j. orton | product | development | design
email: website at ortonomy dot co
description: > # this means to ignore newlines until "baseurl:"
  Personal site of Gregory J. Orton, Product owner & software engineer.

# Server settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ortonomy.co" # the base hostname & protocol for your site, e.g. http://example.com
port: 4000
host: 0.0.0.0
twitter_username: ortonomy_
github_username:  ortonomy

# Files to exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - dev
  - .tern-project
  - .DS_Store
  - design/

# Build settings
markdown: kramdown
theme:
plugins:
  - jekyll-pug

collections:
  sections:
    output: false

